import { proposal } from '../../proposal/source/content.mjs'
import { concepts, presentationThemes } from './content.mjs'

// Client slides contain scope and timing only. Do not copy pricing or payment fields.
export const mvpDeck = {
  title: 'Roote Origin\nSystem',
  subtitle: 'Minimum viable product (MVP)\nand three design directions',
  date: 'Client discussion\n3 October 2026',
  footer: 'ROOTE ORIGIN SYSTEM',
  sourceNote: 'Source: proposed Roote Origin MVP scope, MERN revision, 3 October 2026. Final scope and delivery arrangements are subject to client confirmation.',
  themes: presentationThemes.deck,
  concepts,
  steps: proposal.chain,
  weeks: proposal.delivery.map((item, index) => ({ ...item, detail: [
    'Confirm one design, pilot records, roles, public fields and whether processors combine harvests.',
    'Build MongoDB, the Express/Node.js API and sign-in. Test account access and role restrictions.',
    'Build farm, produce, partner and account forms. Test saving, editing and permitted access.',
    'Add planting, plot and care records. Test required fields, dates and record corrections.',
    'Add harvest IDs, quantities and status. Review the growing-to-harvest workflow with pilot users.',
    'Link processors, lots and recipients. Test origin links and each participant\'s permitted access.',
    'Build public summaries, approvals and QR downloads. Test published, private and unknown IDs.',
    'Connect the catalogue and chosen design. Check mobile, QR and reduced motion. First review round.',
    'Complete the second review round, pilot acceptance and final workflow, permission and device checks.',
    'Launch with HTTPS and backups. Check restore, train operators and confirm the support handover.',
  ][index] })),
  slideCount: 19,
  overview: {
    title: 'Farm discovery and batch origin',
    lead: 'Help people discover partner farms and follow the recorded origin of each produce batch.',
    groups: [
      { title: 'Farm and produce catalogue', body: 'Discover approved farms, crops and batch availability. Find a farm or published batch by ID, QR or partner link.' },
      { title: 'Protected member portal', body: 'Growers, processors and recipients manage their assigned records. Administrators control access and publication.' },
      { title: 'Connected batch history', body: 'Record farming details, harvest dates and quantities, then link each batch to its processor and intended brand owner or distributor.' },
      { title: 'Consumer QR summaries', body: 'Publish a selected summary for each batch. Consumers scan it at a cafe, restaurant or on packaging without logging in.' },
    ],
    note: 'Starting with ube. Members record quantities and availability through the dashboard.',
  },
  batch: {
    title: 'A sample batch journey',
    lead: 'Illustrative example only. All names, dates and records below are fictional.',
    headers: ['Farming', 'Harvest batch', 'Processing', 'Brand or distributor'],
    values: [
      'Farm A\nDavao, Plot 01\nUbe, trellis-grown\nPlanted 1 Feb 2026',
      'SAMPLE-UBE-001\nHarvested 1 Oct 2026\n100 kg recorded\nSaved in batch history',
      'Processor B\nProcessed 2 Oct 2026\nLot PROC-001\nSource SAMPLE-UBE-001',
      'Brand C\nIntended recipient\nLinked to PROC-001\nReceives origin history',
    ],
    note: 'Decision before kickoff: does each processed lot use one harvest batch, or combine multiple harvests?',
    notes: 'This fictional example follows one source harvest batch through processing to its intended brand owner. Farm A, Processor B, Brand C, dates, quantities and identifiers are sample data. Authorized members can read the permitted origin history. The proposed pilot supports one source harvest batch per processed lot. Combined harvests or mixed-farm processing require a revised workflow and scope before commitment. The system records participant-supplied information and does not independently certify authenticity or export eligibility.',
  },
  roles: {
    title: 'Access across the ecosystem',
    lead: 'Proposed access rules for confirmation. The cooperative decides who can see and edit each record.',
    values: [
      ['Participant', 'Can view', 'Can manage'],
      ['Administrator', 'All ecosystem records', 'Users, farms, produce, corrections and publication'],
      ['Grower or farm team', 'Permitted batch history', 'Assigned growing and harvest records'],
      ['Processor', 'Permitted origin and harvest records', 'Assigned processing, lot links and recipients'],
      ['Brand owner or distributor', 'Permitted history of assigned batches', 'Assigned acknowledgement and own partner details'],
      ['Consumer', 'Published profiles and batch summaries', 'None. Public viewing only'],
    ],
    note: 'Proposed MVP: login, password recovery and permission checks in the backend.',
  },
  qr: {
    title: 'One batch, two views',
    lead: 'SAMPLE-UBE-001 continues the fictional example. Consumers see only the approved public summary.',
    memberTitle: 'Authorized member record',
    memberBody: 'Farm A, Davao, Plot 01\nPlanted 1 February 2026\nHarvested 1 October 2026, 100 kg\nProcessor B, Lot PROC-001\nIntended recipient: Brand C\nCare notes and correction history',
    publicTitle: 'Public QR summary',
    publicBody: 'Batch SAMPLE-UBE-001\nUbe from Farm A, Davao\nGrowing summary: trellis-grown ube\nHarvested 1 October 2026\nProcessed by Processor B for Brand C\nApproved details, no login required',
    controls: 'Administrator preview, approval and publish/unpublish controls. Each batch has a stable URL and downloadable PNG/SVG QR artwork.',
    note: 'Farm ID or QR opens a farm profile. Batch ID or QR opens that batch summary.',
    privateNote: 'The fictional example demonstrates two views of the same batch. Members see records their role and assignment permit. Personal contacts, internal notes and commercial details stay private unless the cooperative explicitly approves publication. Physical printing is outside the proposed MVP. Partners must display the QR for the relevant batch on packaging or at the cafe or restaurant. A farm QR opens a farm profile and does not identify a specific serving or batch. Confirm how partners replace displayed QR artwork when the batch changes.',
  },
  designMvp: [
    {
      image: 'presentation/design-redesign/01-root-to-story.png', heroEnd: 654,
      fit: 'A forest-green world where one vine connects origin lookup, partner farms and the cooperative.',
      detail: 'A prominent leaf holds farm or batch lookup. Farm previews follow the vine down to the people behind the roots.',
      motion: 'A root drops beside the green trellis. The vine rises to the lookup leaf, then the scroll descends through stories, partner farms and leadership.',
      status: 'Static design concept. Illustrative imagery and sample records. Motion and mobile layouts are proposed.',
      detailTitle: 'The vine journey and origin lookup',
      detailLead: 'The new opening makes lookup visible within the connected plant story.',
      beats: [
        { title: 'Lookup in the leaf', body: 'Enter a farm or batch ID, or scan its QR, to open the corresponding public page.' },
        { title: 'Farms along the vine', body: 'Scroll downward through the cooperative story and partner farm previews.' },
        { title: 'People at the roots', body: 'The soil and root section introduces cooperative leadership.' },
      ],
    },
    {
      image: 'presentation/design-redesign/02-grown-together.png', heroEnd: 613,
      fit: 'Warm grower photography and an early farm directory make the cooperative easy to explore.',
      detail: 'Visitors search farms or produce, filter the catalogue and open a farm profile. A separate lookup area resolves farm and batch IDs.',
      motion: 'Photographs reveal gently as the page moves. Farm records settle into readable rows, while origin lookup stays easy to reach.',
      status: 'Static design concept. Illustrative imagery and sample records. Motion and mobile layouts are proposed.',
      detailTitle: 'Growers, farms and a clear next step',
      detailLead: 'The editorial opening leads directly into the catalogue and batch lookup.',
      beats: [
        { title: 'Meet the growers', body: 'A warm portrait and a clear farm link introduce the cooperative.' },
        { title: 'Browse the catalogue', body: 'Search farms or produce, then filter by crop and location.' },
        { title: 'Open the origin', body: 'Farm and batch IDs lead to the right public profile or approved summary.' },
      ],
    },
    {
      image: 'presentation/design-redesign/03-purple-to-world.png', heroEnd: 770,
      fit: 'Bold purple-yam imagery leads into the recorded origin behind each harvest.',
      detail: 'A sample batch summary introduces the farm, harvest, processor and recipient. Visitors can explore produce or find a specific batch.',
      motion: 'The yam moves as the product story opens into its origin record. Purple and pale sections guide visitors toward farms and batch lookup.',
      status: 'Static design concept. Illustrative imagery and sample records. Motion and mobile layouts are proposed.',
      detailTitle: 'The product and its recorded origin',
      detailLead: 'A strong product opening connects visitors to the batch information behind it.',
      beats: [
        { title: 'Ube in focus', body: 'The crop takes center stage with routes to produce and batch discovery.' },
        { title: 'A clear origin record', body: 'An illustrative summary shows a farm, harvest, processor and recipient.' },
        { title: 'Continue to a farm', body: 'Public farm and batch links connect the product to its growing story.' },
      ],
    },
  ],
  comparison: {
    title: 'Choosing the public experience',
    lead: 'All three directions use the proposed catalogue, member portal and batch QR features. Select one for implementation.',
    values: [
      ['Direction', 'What it emphasizes', 'What it needs'],
      ['From Root to Story', 'An immersive vine journey with visible lookup', 'Botanical assets, motion and mobile testing'],
      ['Grown Together in Davao', 'Growers and an easy-to-browse farm catalogue', 'Authentic photography and clear farm records'],
      ['Purple to the World', 'Produce and public batch-origin information', 'Product imagery and accurate batch summaries'],
    ],
    note: 'All three are new visual concepts. Confirm the selected design and motion work before finalizing delivery.',
  },
  technology: {
    title: 'Appendix: MERN implementation',
    lead: 'MongoDB, Express, React and Node.js 26, with TypeScript across the frontend and backend.',
    groups: [
      { title: 'React', body: 'Animated public website, farm catalogue, batch summaries and the member dashboard.' },
      { title: 'Express and Node.js 26', body: 'API validation, authenticated access, role permissions and publication controls.' },
      { title: 'MongoDB', body: 'Farms, produce, members, batches, processing links, recipients and record history.' },
    ],
    note: 'UI text and colors stay in constants. Operators edit farm and batch data through the protected dashboard.',
    notes: 'Confirm hosting, authentication, file storage and backup retention at kickoff. Include HTTPS deployment, source files and editing/deployment documentation.',
  },
  timeline: {
    title1: 'Proposed delivery: Weeks 1 to 5',
    title2: 'Proposed delivery: Weeks 6 to 10',
    lead: 'Target: 10 weeks, subject to the selected design, agreed working availability and confirmed pilot workflow.',
    headers: ['Week', 'Milestone', 'Planned output'],
    note1: 'Confirm the chosen redesign before kickoff. Testing starts during development in Week 2.',
    note2: 'Review rounds are proposed for Weeks 8 and 9. Client feedback or scope changes may move launch.',
    notes: 'This is a proposed ten-week plan. The three new visual concepts are static proposals. Confirm how much of the existing prototype can be reused and estimate the chosen redesign, motion and mobile work before committing to the schedule. Confirm weekly availability and the pilot workflow before kickoff. Test each feature as it is built, including permission and persistence checks. First consolidated review is proposed in Week 8, with the second review and final acceptance in Week 9. Confirm the review cadence, support and handover after selecting the working arrangement. Request consolidated feedback within two working days of each review.',
  },
  readiness: {
    title: 'Pilot acceptance and client inputs',
    lead: 'Proposed acceptance checks for the pilot, to confirm before development starts.',
    acceptance: ['A complete farming-to-recipient batch journey', 'Saved records after refresh and re-login', 'Enforced public and private access', 'Correct production QR destinations', 'Mobile, keyboard and reduced-motion checks'],
    inputs: ['Approved identity, photographs and leadership roles', 'Sample farm, batch and partner records', 'Confirmed processing workflow and visibility rules', 'Deployment accounts and one review contact'],
    note: 'Proposed assisted setup: 10 farms, 20 batches and 25 accounts. Ordinary records can be added afterward.',
    notes: 'Proposed acceptance includes Android/Chrome and iPhone/Safari camera checks, a backup restore check, operator training and source/documentation handover. Onboarding numbers describe assisted setup, not software record limits. Confirm who maintains the data and which fields may be public. Launch support and its duration depend on the selected working arrangement. Warehouse stock control, external integrations, mixed-origin blending and independent certification remain outside the proposed initial workflow.',
  },
  handover: {
    title: 'Proposed delivery and support',
    lead: 'Confirm these arrangements after selecting how we will work together.',
    included: [
      'HTTPS production deployment',
      'Database backups and one restore check',
      'Source files and operator documentation',
      'One training session and two revision rounds',
      '30 days of support for delivered defects',
    ],
    boundaries: [
      'Farm catalogue with manually recorded quantities and availability',
      'One harvest batch per processed lot, pending workflow confirmation',
      'QR artwork included. Partners handle physical printing',
      'E-commerce, full ERP stock control and external integrations need separate scope',
    ],
    note: 'Combining harvests or adding new workflows requires revised scope and delivery planning.',
    notes: 'These are proposed delivery and support arrangements, not accepted engagement terms. Confirm revision rounds, training, support duration, handover and ongoing duties for the chosen arrangement. The pilot assumes one source harvest batch per processed lot. If processors combine harvests or farms, revise that workflow before commitment. Source files, HTTPS deployment, backups and one restore check remain proposed delivery items. Ongoing data entry and provider incidents need assigned responsibility.',
  },
  engagement: {
    title: 'How should we work together?',
    question: 'Will this be project-based, a service contract for an agreed period, or direct employment?',
    options: [
      { title: 'Project-based', body: 'Deliver the defined MVP through agreed milestones and a handover.', question: 'Does the engagement end after MVP acceptance and launch support?' },
      { title: 'Service contract', body: 'Provide development and support over an agreed period.', question: 'What duration, work commitment and ongoing support do you expect?' },
      { title: 'Direct employment', body: 'Join the team in a role that supports the system and broader priorities.', question: 'What role, reporting line and responsibilities do you have in mind?' },
    ],
    note: 'Confirm the arrangement, availability and responsibilities before agreeing final engagement terms.',
    notes: 'Project-based work focuses on defined MVP deliverables and acceptance. A service contract provides development and support for an agreed period. Direct employment places ongoing system work within a team role. Confirm expected availability, reporting, responsibilities, handover and ongoing support before finalizing the schedule and engagement terms.',
  },
  decisions: {
    title: 'Decisions for the client discussion',
    items: [
      { title: 'Preferred design', body: 'Which of the three directions best represents the cooperative?' },
      { title: 'Pilot workflow', body: 'Do processors combine harvests? Who records and approves the public batch details?' },
      { title: 'Working arrangement', body: 'Project-based, a service contract for an agreed period, or direct employment?' },
      { title: 'Kickoff readiness', body: 'What weekly availability and review schedule can we commit to?' },
    ],
    note: 'Confirm the design, workflow and working arrangement before finalizing scope and delivery dates.',
  },
}
