// Client proposal copy, prices and visual tokens. Research stays outside the PDF.
export const proposal = {
  title: 'Roote Origin System',
  subtitle: 'MVP scope &\ncosting proposal',
  reference: 'ROOTE-MVP-2026-1003-R3',
  date: '3 October 2026',
  validUntil: '2 November 2026',
  client: 'Ube Farm Cooperative | Davao, Philippines',
  direction: 'From Root to Story',
  pageCount: 7,
  currency: 'PHP',
  colors: { cream: '#F6F3EA', paper: '#FFFFFF', purple: '#542A69', green: '#35583C', ink: '#263A2D', muted: '#637064', border: '#D6DBCB', lavender: '#E7DCEA', sage: '#C2CE9F' },
  summary: 'A memorable farm discovery website supported by a protected system that follows each produce batch from farming and harvest to its processor and intended brand owner or distributor. Ube is the first crop.',
  classification: 'Animated farm inventory + ecosystem portal + batch QR traceability',
  objective: 'Help visitors discover the cooperative\'s farms and produce, give authorized ecosystem members access to connected batch records, and let consumers scan a public summary for the specific batch behind a partner product.',
  basis: 'This revised quotation includes building a new Roote Origin backend and reusing the existing From Root to Story prototype. It replaces the earlier PHP 60,000 landing-page-only quotation; PHP 220,000 is the combined project total, not an additional charge on top of it. Prior payments or separately agreed prototype fees will be reconciled in the final agreement.',
  assumption: 'Confirmed scope: build the Roote Origin backend as part of this MVP. The new system includes protected accounts, database records, batch workflows and approved public QR summaries.',
  timeline: '10 weeks',
  timelineDetail: 'Target: 10 working weeks after written scope approval, complete kickoff inputs and initial payment. Weeks are sequential delivery targets, not fixed calendar dates. Client review, missing data or approved scope changes may extend the schedule.',
  total: 220000,
  onboarding: { farms: 10, batches: 20, accounts: 25 },
  revisions: 2,
  warrantyDays: 30,
  negotiation: 'The proposed project fee, payment terms and delivery arrangements are negotiable. Final costing will be mutually agreed in writing based on the approved scope and schedule.',
  additionalFeatures: 'Additional features, integrations, major design changes or expanded workflows will incur additional cost depending on complexity and negotiations. A separate quotation and any timeline adjustment will be agreed in writing before that work begins.',
  scope: [
    { title: 'Animated landing page', detail: 'Retain the root drop, green trellis, growing vine, tip-leaf lookup, descending stories, partner leaves and root leadership board. Include mobile layouts, skip-intro and reduced-motion reading.' },
    { title: 'Farm & produce inventory', detail: 'Search and filter approved farms and their produce under Roote Origin. Show public profiles, crop/variety, harvest or availability information and published batch links. Start with ube; the data model allows other produce.' },
    { title: 'Ecosystem accounts & roles', detail: 'Invite/login, password recovery and a member dashboard for administrators, growers, processors, brand owners and distributors. Authorized members can read the full permitted batch history; editing is limited by role and assignment.' },
    { title: 'Farming & harvest records', detail: 'Unique batch ID; farm, plot/site, grower, produce/variety, planting date, agreed farming activities and input notes; harvest date, quantity and unit. Include validation, status and a dated edit history.' },
    { title: 'Processor & recipient links', detail: 'Record who processed the batch, when and where, link the source harvest batch to its processed lot, and identify the intended brand owner or distributor. Preserve the origin chain for authorized members.' },
    { title: 'Public per-batch QR', detail: 'Preview and publish an approved consumer summary on a stable batch URL. Download QR artwork in PNG/SVG for partner cafes, restaurants or packaging. Scanning or entering a batch ID opens that specific summary.' },
    { title: 'Admin editing & pilot setup', detail: 'Manage farms, produce, partners, users, batches, public visibility and manually recorded availability. Assisted setup for up to 10 farms, 20 batches and 25 accounts; normal self-service records can be added afterward.' },
    { title: 'Quality, launch & handover', detail: 'Responsive and role-access testing; HTTPS deployment; basic public-page SEO; database backup setup and one restore check; source, documentation, one training session and 30-day in-scope defect support.' },
  ],
  technical: 'MERN stack: MongoDB database, Express API on Node.js 26 and React frontend; TypeScript across frontend/backend. Verify the runtime and hosted MongoDB, authentication and storage plans at kickoff. One cooperative ecosystem, English and one production deployment.',
  editingNote: 'Interface text and colors stay in a centralized constants file. Operational farm, produce and batch data is edited through the protected dashboard and stored in the database.',
  inventoryNote: 'Inventory means a farm/produce catalogue with recorded batch quantities and manually maintained availability. It does not include a full warehouse ledger, reservations, sales orders, POS, invoicing or real-time stock synchronization.',
  chain: [
    { title: 'Farm & growing', detail: 'Origin, planting and care' },
    { title: 'Harvest batch', detail: 'Date, quantity and ID' },
    { title: 'Processor', detail: 'Processing and lot link' },
    { title: 'Brand / distributor', detail: 'Intended recipient' },
  ],
  roles: [
    { role: 'Administrator', read: 'All records in this ecosystem.', write: 'Users, farms, produce, batch corrections and publication approval.' },
    { role: 'Grower / farm team', read: 'Authorized batch histories and linked partners.', write: 'Assigned farm, growing and harvest records.' },
    { role: 'Processor', read: 'Authorized origin and harvest details.', write: 'Assigned processing events, lot links and recipients.' },
    { role: 'Brand owner / distributor', read: 'Full permitted history of assigned batches.', write: 'Assigned receipt/allocation acknowledgement and own partner details.' },
    { role: 'Consumer / public visitor', read: 'Published farm pages and approved batch summaries.', write: 'No backend editing; no login needed to scan.' },
  ],
  privateSummary: 'Member view: agreed farming details, harvest and processing data, linked recipients and record history. Server-side permission checks restrict access by role and batch assignment; the cooperative approves the visibility rules in Week 1.',
  publicSummary: 'Consumer view: batch ID, produce, farm/location, approved growing summary, harvest date, processor and brand/distributor names where approved. Personal contacts, internal notes and commercial information remain private unless explicitly approved for publication.',
  qrNote: 'Farm lookup and farm QR open a farm profile. Batch lookup and batch QR open a batch summary. Administrators can unpublish a summary without deleting its private history. A stable URL keeps printed QR artwork usable after approved content updates; physical printing is excluded.',
  traceabilityBoundary: 'The MVP records information supplied by ecosystem participants. QR traceability does not independently certify authenticity, organic status, export eligibility or regulatory compliance. The initial workflow supports one source harvest batch per processed lot; mixed-origin blending and complex split/merge accounting require separate scope.',
  costItems: [
    { title: 'Public landing page & inventory', detail: 'Prototype refinement, public farm/produce catalogue, profiles and responsive reading view.', amount: 60000 },
    { title: 'Backend foundation & member access', detail: 'Database/API, authentication, roles, server-side access checks and member navigation.', amount: 45000 },
    { title: 'Batch records & traceability workflow', detail: 'Farming, harvest, quantities/status, processor/recipient links, admin forms and edit history.', amount: 55000 },
    { title: 'Consumer summaries & batch QR', detail: 'Publication approval, public batch pages, ID/QR lookup and downloadable artwork.', amount: 25000 },
    { title: 'QA, security checks & pilot review', detail: 'Permissions, public/private separation, mobile/camera tests and two revision rounds.', amount: 20000 },
    { title: 'Deployment, training & handover', detail: 'HTTPS launch, backups/restore check, documentation, training and launch defect support.', amount: 15000 },
  ],
  pricingRationale: 'PHP 220,000 is a scope-based estimate for a focused custom full-stack MVP serving a Davao cooperative. It includes the existing visual direction plus operational records, permissions and public batch pages. Provider packages differ; this is a negotiable project estimate, not a statistical Davao market average.',
  payment: [
    { label: 'Kickoff', percent: 40, trigger: 'Written scope approval; before Week 1 work begins.' },
    { label: 'Core records review', percent: 30, trigger: 'Week 5: accepted farm, growing and harvest workflows on staging.' },
    { label: 'MVP acceptance', percent: 20, trigger: 'Week 9: accepted end-to-end flow and consolidated revisions.' },
    { label: 'Launch & handover', percent: 10, trigger: 'Week 10: before production launch and source transfer.' },
  ],
  domainBudget: { min: 1000, max: 3500 },
  hostingBudget: { min: 2500, max: 5000 },
  maintenance: { amount: 4000, hours: 4 },
  recurringNote: 'Operating allowance: PHP 2,500-5,000/month for a small Node.js/Express API, MongoDB hosting, authentication/file storage, backups and essential service usage; domain PHP 1,000-3,500/year. These are planning allowances, not provider quotations. Client-owned accounts pay actual charges; traffic, storage, email usage, exchange rates and plan changes affect cost.',
  maintenanceNote: 'Optional maintenance: PHP 4,000/month for up to four hours of routine checks, minor fixes/updates and support. New features and extra hours are separately quoted. This service is not automatically billed and is separate from the included 30-day defect support.',
  yearBudgetNote: 'Project fee + 12 months of operating allowance + domain. Excludes optional maintenance, premium domains, paid asset licenses, excess provider usage and applicable taxes. Any applicable tax treatment will be stated in the final quotation/invoice.',
  delivery: [
    { week: 'Week 1', title: 'Confirm the system', detail: 'Approve fields, roles, public/private rules, pilot data, one design direction and the batch workflow.' },
    { week: 'Week 2', title: 'Build the foundation', detail: 'Set up MongoDB, the Express/Node.js API, authentication, environments and server-side access rules.' },
    { week: 'Week 3', title: 'Organize the ecosystem', detail: 'Build farm, produce, partner and account management; prepare the public inventory structure.' },
    { week: 'Week 4', title: 'Capture farming details', detail: 'Implement planting, plot/site, care/input notes and authorized record editing.' },
    { week: 'Week 5', title: 'Track harvest batches', detail: 'Implement batch IDs, harvest dates, quantities, availability/status and record history.' },
    { week: 'Week 6', title: 'Connect processing & recipients', detail: 'Link processors, processed lots, brand owners and distributors to their source batches.' },
    { week: 'Week 7', title: 'Publish the consumer view', detail: 'Build approved batch summaries, publication controls, stable URLs and QR downloads.' },
    { week: 'Week 8', title: 'Connect the landing experience', detail: 'Integrate live public inventory, lookup and batch links; refine mobile and scroll behavior.' },
    { week: 'Week 9', title: 'Review & accept the pilot', detail: 'Run workflow, role, QR and device checks; complete two consolidated in-scope revision rounds.' },
    { week: 'Week 10', title: 'Launch & transfer', detail: 'Configure HTTPS/backups, check restore, train operators, hand over source and start defect support.' },
  ],
  acceptance: [
    'An authorized grower, processor and recipient can complete the agreed batch journey; linked records persist after refresh and re-login.',
    'Public inventory shows only approved farms/produce and batch links. Farm IDs/links and batch IDs/QRs resolve to their respective pages.',
    'Logged-out and unauthorized API requests cannot read private or unassigned records; role-restricted edits and publication controls are enforced.',
    'A production QR opens the correct published summary without login; unpublished/unknown IDs and denied camera access have clear recovery states.',
    'Mobile, keyboard and reduced-motion views work; Android/Chrome and iPhone/Safari QR checks, backup restore and operator handover are completed.',
  ],
  clientInputs: 'Provide the approved cooperative identity/photos, Sir Marco\'s official roles, pilot farm/produce/batch records, processor and brand/distributor details, role assignments and public-field consent. Confirm the workflow and data visibility, supply client-owned service accounts, and return consolidated feedback within two working days of each review.',
  onboardingNote: 'Assisted onboarding covers up to 10 farms, 20 batches and 25 accounts. These are setup allowances, not software record limits. Creating ordinary records through delivered forms is included; bulk migration, developer-assisted entry beyond the allowance or new record types are separately negotiated.',
  revisionsNote: 'Two consolidated revision rounds refine the agreed MVP. A new design concept or changed workflow is a scope change. The 30-day defect-support period starts at launch and covers defects in delivered features; ongoing data entry, new features, provider outages and 24/7 incident response are excluded.',
  exclusions: [
    'E-commerce, payments, POS, accounting, shipment tracking and full warehouse/ERP stock control.',
    'Mixed-origin batch blending, complex split/merge reconciliation and automated stock reservations.',
    'Existing-system integrations, bulk legacy migration, IoT/sensor feeds and offline/native apps.',
    'Blockchain, independent certification, export compliance verification and advanced analytics.',
    'Independent multi-tenant organizations, extra languages, major new 3D scenes and media production.',
  ],
  approval: 'For client discussion. Final scope, total fee, operating arrangements, schedule and payment terms must be mutually confirmed in writing before work begins.',
  // Private research record only; intentionally excluded from the client PDF.
  research: {
    checkedOn: '3 October 2026',
    caveat: 'Vendor-advertised starting points are not like-for-like quotations or a measured Davao market average. The project fee and PHP operating allowances are the proposal author\'s estimates.',
    benchmarks: [
      { name: 'NECXSOFT, Davao', url: 'https://necxsoft.com/', note: 'Vendor displays a Starter estimate around PHP 290,000+ and describes custom web-app timelines of 4-12+ weeks. Different team/inclusions from this focused pilot.' },
      { name: 'Blackbyrds Digital, Philippines', url: 'https://www.blackbyrds.digital/reports/philippine-software-pricing', note: 'Its own 2026 custom-software rate card starts at PHP 150,000; published band PHP 150,000-600,000+. This is one studio\'s pricing, not a national average.' },
    ],
  },
}
