import fs from 'node:fs/promises'
import sharp from 'sharp'

const input = 'design/assets/story', output = 'public/images/story'
await fs.mkdir(output, { recursive: true })
const report = []
const manifest = {}
for (const variant of ['desktop', 'phone']) {
  const folder = variant === 'desktop' ? 'frames' : 'frames-phone'
  await fs.mkdir(`${output}/${variant}`, { recursive: true })
  const originals = (await fs.readdir(`${input}/${folder}`)).filter(name => name.endsWith('.png')).sort()
  if (originals.length !== 72) throw new Error(`${variant}: expected all 72 original renders`)
  const count = variant === 'phone' ? 40 : 60
  const frames = Array.from({length:count},(_,index)=>originals[Math.round(index*(originals.length-1)/(count-1))])
  for (const [index,name] of frames.entries()) {
    const destination = `${output}/${variant}/${String(index).padStart(3,'0')}.webp`
    await sharp(`${input}/${folder}/${name}`).resize({width:variant==='phone'?480:1280,withoutEnlargement:true}).webp({ quality: 68 }).toFile(destination)
  }
  // Remove obsolete generated delivery frames when the authored density changes.
  for (const name of await fs.readdir(`${output}/${variant}`)) if(/^\d{3}\.webp$/.test(name) && Number(name.slice(0,3))>=count) await fs.unlink(`${output}/${variant}/${name}`)
  await fs.copyFile(`${output}/${variant}/000.webp`,`${output}/${variant}-start.webp`)
  await fs.copyFile(`${output}/${variant}/${String(count-1).padStart(3,'0')}.webp`,`${output}/${variant}-end.webp`)
  const meta = await sharp(`${output}/${variant}/000.webp`).metadata()
  const bytes = await Promise.all(frames.map((_,index) => fs.stat(`${output}/${variant}/${String(index).padStart(3,'0')}.webp`).then(stat=>stat.size)))
  report.push({variant, width:meta.width,height:meta.height,count:frames.length,bytes:bytes.reduce((a,b)=>a+b,0)})
  await sharp(`${input}/${variant === 'phone' ? 'handoff-phone' : 'handoff'}.png`).webp({quality:88,alphaQuality:95}).toFile(`${output}/handoff-${variant}.webp`)
  const cutout = `${input}/${variant === 'phone' ? 'handoff-phone' : 'handoff'}.png`
  const {data,info} = await sharp(cutout).ensureAlpha().raw().toBuffer({resolveWithObject:true})
  let left=info.width,top=info.height,right=0,bottom=0
  for(let y=0;y<info.height;y++)for(let x=0;x<info.width;x++)if(data[(y*info.width+x)*4+3]>0){left=Math.min(left,x);top=Math.min(top,y);right=Math.max(right,x);bottom=Math.max(bottom,y)}
  const bounds={left,top,width:right-left+1,height:bottom-top+1}
  await sharp(cutout).extract(bounds).webp({quality:88,alphaQuality:100}).toFile(`${output}/subject-${variant}.webp`)
  await sharp(`${input}/clean-${variant}.png`).resize({width:meta.width}).webp({quality:88}).toFile(`${output}/clean-${variant}.webp`)
  manifest[variant]={base:`/images/story/${variant}/`,start:`/images/story/${variant}-start.webp`,end:`/images/story/${variant}-end.webp`,clean:`/images/story/clean-${variant}.webp`,handoff:`/images/story/handoff-${variant}.webp`,subject:`/images/story/subject-${variant}.webp`,width:meta.width,height:meta.height,count,bytes:bytes.reduce((a,b)=>a+b,0),subjectWidth:bounds.width,subjectHeight:bounds.height,bounds:{x:left/info.width,y:top/info.height,width:bounds.width/info.width,height:bounds.height/info.height},attachment:{x:(left+bounds.width/2)/info.width,y:top/info.height}}
  manifest[variant].frames=frames.map((_,index)=>`/images/story/${variant}/${String(index).padStart(3,'0')}.webp`)
}
await sharp(`${input}/yam-roots.png`).resize({width:800,withoutEnlargement:true}).webp({quality:86,alphaQuality:95}).toFile(`${output}/yam.webp`)
await fs.writeFile(`${input}/manifest.json`,JSON.stringify(report,null,2))
await fs.writeFile('src/constants/storyAssets.ts',`/** Generated by npm run assets:story from retained PNG originals. */\nexport const STORY_ASSETS = ${JSON.stringify(manifest,null,2)} as const\n`)
console.log(JSON.stringify(report))
